### ISSUE TITLE
release first version

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zbus#11]
We have been using zbus for couple of months now and it seems we have reach something stable enough that we could release a first version.

Doing so would allow us to lock down version in 0-OS code base and allow us to creates some new milestones to prioritize work here.

**Comment by zaibon** [comment]
created the draft: https://github.com/threefoldtech/zbus/releases/tag/untagged-e60b6cbe952370217641
@muhamadazmy  let me know what you think about releasing soon

**Comment by muhamadazmy** [comment]
@zaibon Yeah, it's a good idea. We already using it for sometime without needed changes or fixes. We can release this version. And then prepare for next version that will support rust.

**Comment by zaibon** [comment]
https://github.com/threefoldtech/zbus/releases/tag/v0.1.0
