### ISSUE TITLE
zbus: improve docu & improve to understand just a little

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/zbus#20]
- when generating code add on top of file if the file is generated (e.g. in example) and what was used to generate
- explain in more detail what needs to be done to generate code (so example with more bash scripts and better readme)
- put manual in mdbook format (use publtools see kristof)

**Comment by muhamadazmy** [comment]
Updated [readme](https://github.com/threefoldtech/zbus/blob/master/README.md)
